spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
#        1부터 시작하는 인덱스 파라미터
#        pageNumber 등 pageable 데이터는 인덱스 0기준으로 조회됨
#        one-indexed-parameters: true

logging.level:
#  콘솔이 아닌 로그로 sql을 남기기 위해 사용
  org.hibernate.SQL: debug
#  쿼리 나갈 떄 파라미터까지 확인할 수 있는 설정
#  org.hibernate.type: trace
